terasolunaorg/terasoluna-gfw-web-blank

- infra/common/META-INF/spring/projectName-env.xml
- pom.xml
added terasoluna-gfw-jodatime. #67
> add add terasoluna-gfw-jodatime & replace DefaultDateFactoru -> DefaultJodaTimeDateFactory #67

- pom.xml
> reversion 1.1.0 -> 5.0.0 #69

- src/main/resources/META-INF/spring/projectName-domain.xml
> Support wildcard codelistfiles import #71

- src/main/resources/ValidationMessages.properties
Please review #75 ,and merge to master branch.
> Added ValidationMessages.properties #75

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis2.sh
- create-maven-archetype-mybatis3.sh
- pom.xml
> changed description #77

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis2.sh
> modify sed script #80

- pom.xml
#85 
added build-helper-maven-plugin
> added build-helper-maven-plugin #85

- pom.xml
> Add version property of build-helper-maven-plugin. #87

- infra/common/META-INF/spring/projectName-env.xml
- pom.xml
- src/main/resources/logback.xml
> remove mybatis2 #89

- pom.xml
> Upgrade Version to 5.1.0-SNAPSHOT. #93

- pom.xml
> Upgrade Version to 5.0.1-SNAPSHOT. #94

- pom.xml
> Upgrade Version to 1.0.3-SNAPSHOT. #95

- src/main/resources/logback.xml
> Use property to resolve a log output directory. #99

- CONTRIBUTING.md
> add CONTRIBUTING.md #101

- src/main/webapp/WEB-INF/web.xml
> #106: Remove an unnecessary comment in web.xml

- src/main/resources/logback.xml
> #105: improve logback.xml

- src/main/resources/logback.xml
(cherry picked from commit 4e4d0337bed6a90ce589253c0c394090b324936e)
Please review #105 .
> [5.0.x] #105: improve logback.xml

- pom.xml
> Update Tomcat version in pom.xml. #114

- .gitignore
> #117: Ignore IDEA project file from git management

- README.md
> #122: Update version to 5.0.1.RELEASE in README.md

- README.md
> #123: Update version to 1.0.3.RELEASE in README.md

- README.md
(cherry picked from commit 316b57e52936abf3ceced18398fbec011bbd6f2e)
Please review #122 .
> [5.0.x] #122: Update version to 5.0.1.RELEASE in README.md

- pom.xml
> #126: Update to 1.0.4-SNAPSHOT

- pom.xml
> #127: Update to 5.0.2-SNAPSHOT

- .gitignore
(cherry picked from commit 98cac4914fbc71583fe1909610d2ee5da2882dcf)
Please review #117 .
> [5.0.x] #117: Ignore IDEA project file from git management

- .gitignore
(cherry picked from commit 98cac4914fbc71583fe1909610d2ee5da2882dcf)
Please review #117 .
> [1.0.x] #117: Ignore IDEA project file from git management

- infra/jpa/META-INF/spring/projectName-infra.xml
> #133: Change default value of 'hibernate.hbm2ddl.auto' ('none' -> '')

- src/main/webapp/WEB-INF/web.xml
> Add config to disable URL rewriting by default #137

- infra/common/META-INF/spring/projectName-domain.xml
> Add define for importing codelist files using wildcard #145 #71

- infra/common/META-INF/spring/projectName-domain.xml
- infra/common/META-INF/spring/projectName-env.xml
- infra/jpa/META-INF/spring/projectName-infra.xml
- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
- infra/mybatis3/META-INF/spring/projectName-infra.xml
- infra/mybatis3/xxxxxx/yyyyyy/zzzzzz/domain/repository/sample/SampleRepository.xml
- src/main/resources/META-INF/spring/applicationContext.xml
- src/main/resources/META-INF/spring/projectName-domain.xml
- src/main/resources/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/spring-mvc.xml
- src/main/resources/META-INF/spring/spring-security.xml
- src/main/webapp/WEB-INF/web.xml
Please review #143 .
I've copied from https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank.
> Polishing xml files #143

- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
* defaultFetchSize
* proxyFactory
Please review #136 .
> Apply changes for MyBatis 3.3.0 #136

- pom.xml
> Remove terasoluna-gfw-3rdparty #142

- src/main/resources/META-INF/spring/projectName-domain.xml
I've fixed mistake for polishing.
Please review #143 .
> Add schema definition for context namespace #143

- src/main/resources/META-INF/spring/spring-mvc.xml
- src/main/resources/META-INF/spring/spring-security.xml
> correspond to the 'Spring Secuity 4.0.' #158

- pom.xml
(cherry picked from commit 93b06cfe460e7b1efa6bb856f134e535e1e95788)
Please review #142 .
> [5.0.x] Remove terasoluna-gfw-3rdparty #142

- src/main/resources/ValidationMessages.properties
> add validation messages for new constraint validation annotations #156

- pom.xml
> change dependency web to web-jsp. issues:#162

- pom.xml
- unmaven-project.sh
> Update Java version to 1.8 issues:#116

- pom.xml
please review #168 
---
ac3a141d501982a5af3ece802e7ea0ec6a068eec
---
> fixed plugin spell #168

- pom.xml
please review bkprt #168 
---
2b83e99df45d326456d9b33af890c3d200211896
---
> fixed plugin spell

- src/main/resources/META-INF/spring/spring-security.xml
> modify 'auto-config' configuration #159

- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
- pom.xml
> add settings for using CGLIB in MyBatis proxyFactory. issues:#171

- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
Please review #171 .
Removed proxyFactory=CGLIB and added comment in mybatis-config.xml .
> [5.0.x] add comment to mybatis-config.xml for proxyFactory. issues:#171

- CONTRIBUTING.md
> Fix a rule for git commit comments #135

- pom.xml
> Update to 1.0.5-SNAPSHOT #176

- pom.xml
> Update to 5.0.3-SNAPSHOT #177

- pom.xml
> Update to 5.1.1-SNAPSHOT #178

- pom.xml
> Update to 5.2.0-SNAPSHOT #179

- README.md
> Update version to 1.0.4.RELEASE in README.md #184

- README.md
> Update version to 5.0.2.RELEASE in README.md #185

- README.md
> [5.1.x] Update version to 5.1.0.RELEASE in README.md #186

- README.md
> Update version to 5.1.0.RELEASE in README.md #186

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
> Add issue and PR template #191

- pom.xml
> add a dependency to taglibs-standard-jstlel #193

- pom.xml
Please review #195 .
Screen display confirmed to be deployed in the local as operation check.
> Add the type in the description of the dependency #195

- pom.xml
> apply new pom structure #197

- pom.xml
> add new comments to categorize properties #197

- pom.xml
> add gfw-web-dependencies #197

- src/main/resources/META-INF/spring/spring-mvc.xml
> add wordarround to CVE-2016-5007 #201

- src/main/resources/META-INF/spring/spring-mvc.xml
Please review #201.
(cherry picked from commit c90b1b826ddbddf9112a55e1e5cd2f7d4cac8629)
> [5.1.x] add wordarround to CVE-2016-5007 #201

- src/main/resources/META-INF/spring/spring-mvc.xml
Please review #201.
(cherry picked from commit c90b1b826ddbddf9112a55e1e5cd2f7d4cac8629)
> [1.0.x] add wordarround to CVE-2016-5007 #201

- create-maven-archetype.sh
- src/main/resources/META-INF/spring/projectName-codelist.xml
> add codelist xml file #208

- create-maven-archetype.sh
> get rid of mv command error #209

- README.md
> modify description of running application #210

- infra/common/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
> move projectName-codelist.xml, because it used when need to access database only #208

- infra/common/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
Please review #208.
(cherry picked from commit 9902180e2b12231b56539346c469c8930bb90749)
> [5.1.x] move projectName-codelist.xml, because it used when need to access database only #208

- infra/common/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
Please review #208.
(cherry picked from commit 9902180e2b12231b56539346c469c8930bb90749)
> [5.0.x] move projectName-codelist.xml, because it used when need to access database only #208

- create-maven-archetype.sh
- infra/common/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
> [1.0.x] move projectName-codelist.xml, because it used when need to access database only #208

- pom.xml
> update SNAPSHOT version to 1.0.6-SNAPSHOT.#227

- pom.xml
> update SNAPSHOT version to 5.1.2-SNAPSHOT.#227

- pom.xml
> update SNAPSHOT version to 5.2.1-SNAPSHOT.#227

- pom.xml
> update SNAPSHOT version to 5.3.0-SNAPSHOT.#227

- README.md
> update version in README.md.#228

- README.md
> [5.2.x]update version in README.md.#228

- README.md
> [5.1.x]update version in README.md.#228

- README.md
> [1.0.x]update version in README.md.#228

- pom.xml
Please review #237 .
Pending by https://github.com/terasolunaorg/terasoluna-gfw-web-blank/pull/241#discussion_r82978772 .
> delete encoding in pom.xml because it is not used #237

- pom.xml
> add selenium dependency. #245

- src/main/resources/META-INF/spring/spring-mvc.xml
> fix typo in spring-mvc.xml. #247

- pom.xml
> update Postgresql JDBC Driver version. #248

- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
> remove <setting name="aggressiveLazyLoading" value="false" /> in mybatis/mybatis-config.xml

- infra/common/META-INF/spring/projectName-env.xml
> [5.3.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFailure=true in projectName-env.xml

- infra/common/META-INF/spring/projectName-env.xml
Please review #259 .
PR #260の5.2.x版バックポートです。
> [5.2.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFailure=true in projectName-env.xml

- pom.xml
> Modified /pom.xml for Maven Central.#264

- src/main/resources/META-INF/spring/spring-mvc.xml
> Add excludedExceptions #270

- README.md
> [master] explicitly use archetype plugin 2.4 #272

- README.md
> [5.2.x] explicitly use archetype plugin 2.4 #272

- README.md
> [5.1.x] explicitly use archetype plugin 2.4 #272

- README.md
> [5.0.x] explicitly use archetype plugin 2.4 #272

- README.md
> [1.0.x] explicitly use archetype plugin 2.4 #272

- README.md
> [master]Modified version from 5.2.0.RELEASE to 5.3.0.RELEASE.#267

- README.md
> [5.3.x]Modified version from 5.2.0.RELEASE to 5.3.0.RELEASE.#267

- README.md
> [5.2.x]Modified version from 5.2.0.RELEASE to 5.2.1.RELEASE.#267

- README.md
> [1.0.x]Modified version from 1.0.5.RELEASE to 1.0.6.RELEASE.#267

- pom.xml
> [master]Update version to 5.4.0-SNAPSHOT.#282

- pom.xml
> [5.3.x]Update version to 5.3.1-SNAPSHOT.#282

- pom.xml
> [5.2.x]Update version to 5.2.2-SNAPSHOT.#282

- pom.xml
> [1.0.x]Update version to 1.0.7-SNAPSHOT.#282

- pom.xml
> fix ojdbc group ID in pom.xml, match officially group ID  #287

- pom.xml
> [5.3.x] fix ojdbc group ID in pom.xml, match officially group ID  #287

- pom.xml
> [5.2.x] fix ojdbc group ID in pom.xml, match officially group ID  #287

- pom.xml
> [5.1.x] fix ojdbc group ID in pom.xml, match officially group ID  #287

- pom.xml
> [5.0.x] fix ojdbc group ID in pom.xml, match officially group ID  #287

- pom.xml
> [1.0.x] fix ojdbc group ID in pom.xml, match officially group ID  #287

- ISSUE_TEMPLATE.md
> Add Final Solution and Migrating Guide section to Issue Template. #288

- src/main/resources/META-INF/spring/spring-mvc.xml
> Remove definition of trimTokens #300

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.3.x] Remove definition of trimTokens #300

- src/main/resources/logback.xml
> add doctype.#299

- src/main/resources/logback.xml
(cherry picked from commit a063bd06c95213b3a2b843d2db3bcf7cc40b3f8d)
Please review #299.
> [5.3.x] add doctype.#299

- pom.xml
Please review #315 .
This PR is sideport for terasoluna-gfw-web-blank .
> remove selenium.version #315

- pom.xml
(cherry picked from commit 447c27ff790bd7041f40d98dfbcdda3f7d0f684b)
Please review #315 .
This PR is sideport for terasoluna-gfw-web-blank and backport for 5.3.x .
> [5.3.x] remove selenium.version #315

- README.md
> fix archetype version in README.md #318

- pom.xml
> [5.3.x] fix SNAPSHOT version in pom.xml #320

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
> add br tag to make the error page size 513 bytes or more #324

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 46948176a08b51be96e8049f7d4407e4a4f6e4d1)
Please review #324 .
This PR is backport for 5.3.x .
> [5.3.x] add br tag to make the error page size 513 bytes or more #324

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 46948176a08b51be96e8049f7d4407e4a4f6e4d1)
Please review #324 .
This PR is backport for 5.2.x .
> [5.2.x] add br tag to make the error page size 513 bytes or more #324

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 46948176a08b51be96e8049f7d4407e4a4f6e4d1)
Please review #324 .
This PR is backport for 5.1.x .
> [5.1.x] add br tag to make the error page size 513 bytes or more #324

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
(cherry picked from commit 46948176a08b51be96e8049f7d4407e4a4f6e4d1)
Please review #324 .
This PR is backport for 5.0.x .
> [5.0.x] add br tag to make the error page size 513 bytes or more #324

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis3.sh
- create-maven-archetype.sh
> be able to select install in addition to deploy #333

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis3.sh
- create-maven-archetype.sh
(cherry picked from commit 555d711ee320da3cfab6ec1762cfc7a5fadab3f9)
This PR is backport for 5.3.x .
> [5.3.x] be able to select install in addition to deploy #333

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis3.sh
- create-maven-archetype.sh
This PR is backport for 5.2.x .
> [5.2.x] be able to select install in addition to deploy #333

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis3.sh
- create-maven-archetype.sh
This PR is backport for 5.1.x .
> [5.1.x] be able to select install in addition to deploy #333

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis3.sh
- create-maven-archetype.sh
(cherry picked from commit 4717151bc0eb66eb5338eb8aedd0eb2db7b6d06a)
This PR is backport for 5.0.x .
> [5.0.x] be able to select install in addition to deploy #333

- create-maven-archetype-jpa.sh
- create-maven-archetype-mybatis2.sh
- create-maven-archetype.sh
This PR is backport for 1.0.x .
> [1.0.x] be able to select install in addition to depkoy #333

- pom.xml
> Add library for test in pom.xml #343

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> format indent #341

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> [5.3.x] format indent #341

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> [5.2.x] format indent #341

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> [5.1.x] format indent #341

- src/main/webapp/WEB-INF/views/common/error/accessDeniedError.jsp
- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/invalidCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/missingCsrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> [5.0.x] format indent #341

- src/main/webapp/WEB-INF/views/common/error/businessError.jsp
- src/main/webapp/WEB-INF/views/common/error/csrfTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/dataAccessError.jsp
- src/main/webapp/WEB-INF/views/common/error/resourceNotFoundError.jsp
- src/main/webapp/WEB-INF/views/common/error/systemError.jsp
- src/main/webapp/WEB-INF/views/common/error/transactionTokenError.jsp
- src/main/webapp/WEB-INF/views/common/error/unhandledSystemError.html
- src/main/webapp/WEB-INF/views/welcome/home.jsp
> [1.0.x] format indent #341

- README.md
(cherry picked from commit a02ea7f887a2f4fb3db09e0f04d2a8500b0392a6)
Please review #318 .
> [5.3.x] fix archetype version in README.md #318

- pom.xml
> update to 5.5.0-SNAPSHOT #351

- pom.xml
> [5.4.x] update to 5.4.1-SNAPSHOT #351

- README.md
> update version to 5.4.0.RELEASE in README.md #350

- README.md
(cherry picked from commit 9a05694ae7a1c19b7f4a199053179b9d9a128507)
Please review #350.
> [5.4.x] update version to 5.4.0.RELEASE in README.md #350

- README.md
> update readme version to 5.4.1 release #359

- README.md
- pom.xml
> [5.4.x] update version both readme and pom #359

- README.md
- pom.xml
> [5.3.x] update version both readme and pom #359

- pom.xml
- src/main/resources/META-INF/spring/applicationContext.xml
> update to 5.5.0.RC2-SNAPSHOT #365

- pom.xml
> update postgresql driver version #367

- src/main/resources/META-INF/spring/spring-mvc.xml
> Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.4.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.3.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.2.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.1.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- src/main/resources/META-INF/spring/spring-mvc.xml
> [5.0.x]backport_Improve mvc:exclude-mapping Definition of interceptors in spring-mvc.xml for security #312

- pom.xml
- src/main/resources/META-INF/spring/applicationContext.xml
> add comment out the definition of password encoder #370

- pom.xml
Please review #364 .
add encoding property.
> add encoding property #364

- pom.xml
> remove a definition referring to Sonatype Nexus Snapshots #357

- pom.xml
> update postgresql #386

- pom.xml
Please review #364.
It is backport.
(cherry-pick : 2536bd3)
> [backport]add encoding property #364

- pom.xml
(cherry picked from commit 90691676ccb7c6e13be46dc44e1b019786ff0d53)
Please review #357 .
> [backport][5.4.x]remove a definition referring to Sonatype Nexus Snapshots #357

- pom.xml
(cherry picked from commit 90691676ccb7c6e13be46dc44e1b019786ff0d53)
Please review #357 .
> [backport][5.3.x]remove a definition referring to Sonatype Nexus Snapshots #357

- ISSUE_TEMPLATE.md
Please review #388.
- Delete `Final Solution` 
- Delete `Migrating Guide`
- Add version template into `Fix Version/s`
- Change markdown syntax for listing
> update issue template #388

- ISSUE_TEMPLATE.md
- pom.xml
>  update to 5.5.1-SNAPSHOT #391 #382

- src/main/resources/ValidationMessages.properties
> apply @ByteSize #393

- pom.xml
> update jdbc version #369

- pom.xml
> remove SCryptPasswordEncoder #370

- src/main/resources/ValidationMessages.properties
(cherry picked from commit 04371d924d7a557af779cd070f16f7e2fedc18f4)
Please review #393.
> [5.4.x] apply @ByteSize #393

- pom.xml
> update to 5.5.2-SNAPSHOT #399

- ISSUE_TEMPLATE.md
- pom.xml
> update to 5.6.0-SNAPSHOT #399

- pom.xml
> update jdbc version #396

- infra/common/META-INF/spring/projectName-codelist.xml
- infra/common/META-INF/spring/projectName-domain.xml
- infra/common/META-INF/spring/projectName-env.xml
- infra/jpa/META-INF/spring/projectName-infra.xml
- infra/mybatis3/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/applicationContext.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-domain.xml
- src/main/resources/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/spring-mvc.xml
- src/main/resources/META-INF/spring/spring-security.xml
> [5.4.x] replace schema location for Spring from http to https #402

- README.md
(cherry picked from commit f50d97f578db8701bbaf80497a8c5fc32f05a3d9)
Please review #406
> [5.5.1]update release version #406

- README.md
> [5.4.2]update release version #406

- README.md
> update release version #406

- README.md
> fix version to 5.5.1.RELEASE of README #406

- infra/common/META-INF/spring/projectName-codelist.xml
- infra/common/META-INF/spring/projectName-domain.xml
- infra/common/META-INF/spring/projectName-env.xml
- infra/jpa/META-INF/spring/projectName-infra.xml
- infra/mybatis3/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/applicationContext.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-domain.xml
- src/main/resources/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/spring-mvc.xml
- src/main/resources/META-INF/spring/spring-security.xml
Please review #402.
Cherry picked from commit b9bf93c4d88380438a8a7267776834869e46ae45 .
> replace schema location for Spring from http to https #402

- src/main/resources/ValidationMessages.properties
Please review #411.
I checked to able to be override message using VaildationMessages.properties.
> remove validation messages for common libraries #411

- src/main/resources/META-INF/spring/applicationContext.xml
> Add Argon2PasswordEncoder #420

- infra/common/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
> Prepare xml namespace "util" for using SimpleMapCodeList #424

- pom.xml
> update jdbc driver #418

- infra/common/META-INF/spring/projectName-env.xml
- infra/common/log4jdbc.properties
- src/main/resources/logback.xml
> remove log4jdbc-remix #417

- src/main/resources/logback.xml
> Provide trace logs about mapped handler method #414

- pom.xml
> upgrade to hamcrest to 2.x #429

- pom.xml
> upgrade jdbc 42.2.9 #418

- src/main/resources/logback.xml
> change loglevel of Repository to trace to log ResultSet #417

- unmaven-project.sh
> fix scope compile from to runtime in shell of making wtp #437

- README.md
- pom.xml
> update 5.7.0-SNAPSHOT #440

- README.md
- pom.xml
> update 5.6.1-SNAPSHOT #440

- pom.xml
(cherry picked from commit 211facd)
Please review #445.
Original PR #444
> [5.6.x]Change the groupId of the OracleJDBCDriver #445

- README.md
Please review #459 
Confirmation method:
- Grep search for "5.6.0." and confirm that there are no omissions.
> update 5.6.1.RELEASE in README #459

- pom.xml
> update 5.6.2-SNAPSHOT #458

- pom.xml
> update 5.5.3-SNAPSHOT #464

- pom.xml
Reverts terasolunaorg/terasoluna-gfw-web-blank#469
Resolve-#443 .
> Revert "[5.6.x]Update the version of the maven plugin #466", and update Maven War Plugin #443

- infra/jpa/META-INF/spring/projectName-infra.xml
> fixed EntityManager setting for Hibernate #471

- infra/jpa/META-INF/spring/projectName-infra.xml
(cherry picked from commit d7b57c20e1125ebe20c6cf345588002cd11a9b3e)
Please review #472
> [5.6.x] fixed EntityManager setting for Hibernate #471

- pom.xml
(cherry picked from commit 9e66697fb039035dc1f49de1540c5645a71863e2)
Please review #481
> [5.6.x] set source to maven-javadoc-plugin #476

- .gitignore
(cherry picked from commit 9902413d7b9106abece16dc0dbc760284bd25101)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/485.
Removed unnecessary settings from gitignore.
> [5.6.x]Fix gitignore settings #483

- README.md
> update 5.7.0.RELEASE in README.md #487

- README.md
> update 5.6.2.RELEASE in README #489

- pom.xml
> update to 5.8.0-SNAPSHOT. #491

- pom.xml
> update to 5.6.3-SNAPSHOT. #493

- src/main/java/xxxxxx/yyyyyy/zzzzzz/app/welcome/HelloController.java
Please review #502 
As described in #502, it is modified to accept only the GET method.
> replaced RequestMapping with GetMapping #502

- pom.xml
> update dbunit to 2.7.2 #504

- pom.xml
Please review #504 
See https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/504#issuecomment-986364056
> added poi-ooxml dependency #504

- pom.xml
(cherry picked from commit e8bbb4e560dc46b12767378beb8a75f722ceacaf)
Please review #506
See https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/506#issuecomment-987668666
> [5.7.x] added poi-ooxml dependency #504

- pom.xml
> Match postgresql and ojdbc versions with Spring Boot #510

- pom.xml
(cherry picked from commit 8684a9bf2a8d9e33a1e54adb74b83e64fae02e29)
Please review #512.
> Match postgresql and ojdbc versions with Spring Boot #512

- src/main/resources/logback.xml
> changed log format #514

- README.md
- pom.xml
> update SNAPSHOT to 5.7.2 #518

- README.md
> Change the version in README to the latest version #520

- .github/ISSUE_TEMPLATE/3-backport-issue.md
> improved backport-issue template #522

- .gitignore
Please review #525
I made a spelling error, which has been corrected.
> corrected spelling of factorypath #525

- pom.xml
> update library version for 5.7.2 #528

- src/main/resources/META-INF/spring/spring-security.xml
> fixed FilterSecurityInterceptor setting #530

- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/535
> Change to default settings

- parts/JavaConfig/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ApplicationContextConfig.java
- parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/537
> Algorithm change in PasswordEncoders #537

- create-maven-archetype.sh
> fix typo #540

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
> update SNAPSHOT to 5.8.1. #547

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
> fix requestMatcher #549

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
> update 5.9.0-SNAPSHOT. #551

- parts/Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/common/error/CommonErrorController.java
> add missing thymeleaf file. #553

- parts/Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/common/error/CommonErrorController.java
(cherry picked from commit b506d06bbd0282a7cd52ed7d70d26604397fba12)
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/555
> [5.8.x]add missing thymeleaf file. #553

- README.md
- pom.xml
Please review #557 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-2394
> update 5.7.3-SNAPSHOT. #557

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #559 
https://terasolunaorg.atlassian.net/browse/TSF4J5-2394
> update 5.8.2-SNAPSHOT #559

- testScript/addTestResource.sh
- testScript/parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.jsp
- testScript/parts/JSP/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SeleniumContextConfig.java
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SpringMvcMockMvcConfig.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/Thymeleaf/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.html
- testScript/parts/Thymeleaf/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
- testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestService.java
- testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestServiceImpl.java
- testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/MockTestController.java
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/TestErrorController.java
Please review #563 .
Added test to check internally.
Added a shell to apply after project generation.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-2805
> Add an internal test implementation to the Blank project #563

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
- parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
Please review #567
Added @EnableAspectJAutoProxy to SpringMvcConfig.
Add the aop:aspectj-autoproxy tag to match the above settings and align the definitions in the XML version.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-3001
> Fixed SpringAOP not working.  #567

- testScript/addTestResource.sh
- testScript/parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/errortest/otherError.jsp
- testScript/parts/JSP/projectName-web/src/test/resources/META-INF/spring/mockmvc.properties
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
- testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestService.java
- testScript/parts/base/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/domain/service/errortest/MockTestServiceImpl.java
- testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/MockTestController.java
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/TestErrorController.java
Please review #571 .
Added test to check internally.
Added a shell to apply after project generation.
Regarding BackPort, we have fixed incompatible parts and deleted the JavaConfig version.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-2801
> BackPort:Add an internal test implementation to the Blank project #571

- parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/layout/footer.jsp
- parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/welcome/home.jsp
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/576.
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3250.
> Add footer #TSF4J5-3250

- create-maven-archetype.sh
> Modified shell scripts to add javaconfig version #581

- parts/JavaConfig-NoORM/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameInfraConfig.java
- parts/JavaConfig/projectName-env/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameEnvConfig.java
- parts/XMLConfig/projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SeleniumContextConfig.java
Please review #583 
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-3812
Unnecessary import statements were removed.
> update boot to 3.2.0 #583

- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
> Change helllotest assert content #588

- pom.xml
- src/main/webapp/WEB-INF/views/welcome/home.jsp
- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/FunctionTestSupport.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/WebDriverOperations.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/ChromeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/EdgeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/FirefoxDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverType.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
> add webdriver settings #587

- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/587#issuecomment-1888837160 .
> fix mock settings #587

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #592 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3940
> library version up #592

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #594.
relates to [TSF4J5-4102](https://terasolunaorg.atlassian.net/browse/TSF4J5-4102)
> add parameters option. #594

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
Please review #598
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4214
> corrected withDefault settings #598

- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/600.
relates to [TSF4J5-4307](https://terasolunaorg.atlassian.net/browse/TSF4J5-4307).
> Format to JDK21. #600

- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
Please review #601.
relates to [TSF4J5-4312](https://terasolunaorg.atlassian.net/browse/TSF4J5-4312).
> [5.7.x] Format to JDK21. #601

- create-maven-archetype.sh
Please review #604.
relates to [TSF4J5-4360](https://terasolunaorg.atlassian.net/browse/TSF4J5-4360).
> Added debugging options during deployment #604

- create-maven-archetype.sh
(cherry picked from commit 9c95891d57c8c126567b29c3803eae097ff4b2dc)
Please review #606.
relates to [TSF4J5-4363](https://terasolunaorg.atlassian.net/browse/TSF4J5-4363).
> [5.7.x]Added debugging options during deployment #604

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #609.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4332
> update 5.10.0-SNAPSHOT. #609

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringSecurityConfig.java
> fixed how AntPathRequestMatcher is implemented #608

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #612.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4378
> [5.9.x]update 5.9.1-SNAPSHOT. #612

- README.md
- pom.xml
Please review #614.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4399
> [1.8.x]update 5.7.4-SNAPSHOT. #614

- parts/base/src/main/resources/logback.xml
Please review #616.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4349
> fix logback settings #616

- parts/base/src/main/resources/logback.xml
Please review #618 .
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2897
> update Hibernate log output settings. #618

- src/main/resources/logback.xml
(cherry picked from commit 0022214614d772018aad658e8a6ec90c8ab1ba3c)
Please review #620 .
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4608.
> [5.7.x]fix logback settings #620

- src/main/resources/logback.xml
Please review #622 
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2910
> update Hibernate log output settings. #622

- src/main/resources/logback.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/622#issuecomment-2151143221
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2910
> changed the logger class to one compatible with hibernate 5. #622

- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/config/SeleniumContextConfig.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/ChromeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/EdgeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/FirefoxDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/HeadlessWebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverType.java
- testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
- testScript/parts/base/projectName-selenium/src/test/resources/wdm.properties
Please review #625.
relates to [TSF4J5-4628](https://terasolunaorg.atlassian.net/browse/TSF4J5-4628).
> Make it headless compatible. #625

- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/FunctionTestSupport.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/WebDriverOperations.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/ChromeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/EdgeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/FirefoxDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/HeadlessWebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverType.java
- testScript/parts/base/projectName-selenium/src/test/resources/META-INF/spring/selenium.properties
- testScript/parts/base/projectName-selenium/src/test/resources/wdm.properties
Please review #627.
relates to [TSF4J5-4638](https://terasolunaorg.atlassian.net/browse/TSF4J5-4638).
> [5.7.x] Make it headless compatible. #627

- parts/JSP/projectName-web/src/main/webapp/WEB-INF/views/common/include.jsp
- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
- parts/XMLConfig-JPA/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
- parts/XMLConfig-JSP/projectName-web/src/main/webapp/WEB-INF/web.xml
- parts/XMLConfig-MyBatis3/projectName-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
- parts/XMLConfig-MyBatis3/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
- parts/XMLConfig-NoORM/projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
- parts/XMLConfig-NoORM/projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
- parts/XMLConfig-NoORM/projectName-domain/src/main/resources/META-INF/spring/projectName-infra.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/webapp/WEB-INF/web.xml
- parts/XMLConfig/projectName-domain/src/main/resources/META-INF/spring/projectName-codelist.xml
- parts/XMLConfig/projectName-domain/src/main/resources/META-INF/spring/projectName-domain.xml
- parts/XMLConfig/projectName-env/src/main/resources/META-INF/spring/projectName-env.xml
- parts/XMLConfig/projectName-web/src/main/resources/META-INF/spring/applicationContext.xml
- testScript/parts/XMLConfig/projectName-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
- testScript/parts/XMLConfig/projectName-web/src/test/resources/META-INF/spring/spring-mvc-mockmvc.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/631#issuecomment-2303376302
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4905
> minor formatting corrections #631

- infra/common/META-INF/spring/projectName-codelist.xml
- infra/common/META-INF/spring/projectName-domain.xml
- infra/common/META-INF/spring/projectName-env.xml
- infra/jpa/META-INF/spring/projectName-infra.xml
- infra/mybatis3/META-INF/mybatis/mybatis-config.xml
- infra/mybatis3/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/applicationContext.xml
- src/main/resources/META-INF/spring/projectName-codelist.xml
- src/main/resources/META-INF/spring/projectName-domain.xml
- src/main/resources/META-INF/spring/projectName-infra.xml
- src/main/resources/META-INF/spring/spring-mvc.xml
- src/main/resources/META-INF/spring/spring-security.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/632#issuecomment-2311849856
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4890
> [5.7.x] minor formatting corrections #632

- src/main/webapp/WEB-INF/web.xml
Please review #637 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5008
> [5.7.x] Changed to Servlet 4.0. #637

- LICENSE.txt
Please review #641 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5177
> add LICENSE.txt #641

- LICENSE.txt
> [5.7.x] add LICENSE.txt #643

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
> add <developers> and <scm> on pom.xml #645

- create-maven-archetype.sh
- pom.xml
> [5.7.x] add <developers> and <scm> on pom.xml #647

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #651 
Fixed how to specify war generated by maven-war-plugin according to the documentation.
https://maven.apache.org/plugins/maven-war-plugin/usage.html#invocation-of-war-exploded-goal
> update the plugin version #651

- src/main/resources/META-INF/spring/applicationContext.xml
Please review #653 
related to [TSF4J5-5880](https://terasolunaorg.atlassian.net/browse/TSF4J5-5880)
> fix bcprov comment. #653

- src/main/java/xxxxxx/yyyyyy/zzzzzz/app/welcome/HelloController.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/FunctionTestSupport.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/WebDriverOperations.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/ChromeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/EdgeDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/FirefoxDriverFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/webdrivers/WebDriverManagerFactoryBean.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/MockTestController.java
- testScript/parts/base/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/app/errortest/TestErrorController.java
Please review #632.
relates to [TSF4J5-5867](https://terasolunaorg.atlassian.net/browse/TSF4J5-5867).
> [5.7.x] import reorganization. #632

- parts/JavaConfig-MyBatis3/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameInfraConfig.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/631#issuecomment-2642503618
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5862
> fix javadoc #631

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #659.
relate to [TSF4J5-5960](https://terasolunaorg.atlassian.net/browse/TSF4J5-5960)
> remove extra vesion define, update jdbc version. #659

- pom.xml
Please review #661 .
relate to [TSF4J5-5973](https://terasolunaorg.atlassian.net/browse/TSF4J5-5973)
> remove extra definition, update jdbc. #661

- parts/JavaConfig/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ApplicationContextConfig.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/631#issuecomment-2670811547
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5973
> corrected formatting of comments #631

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
Please review #664
relate to [TSF4J5-6118](https://terasolunaorg.atlassian.net/browse/TSF4J5-6118)
> update ojdbc driver. #664

- pom.xml
Please review #666 .
relate to [TSF4J5-6127](https://terasolunaorg.atlassian.net/browse/TSF4J5-6127)
> update ojdbc driver. #666

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
> 5.11.0-SNAPSHOT. #669

- README.md
- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
> 5.10.1-SNAPSHOT. #670

- README.md
- pom.xml
> 5.7.5-SNAPSHOT. #671

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
- parts/JavaConfig-NoORM/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameDomainConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
> Modify Javadoc #668

- parts/XMLConfig-JSP/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
- parts/XMLConfig-Thymeleaf/projectName-web/src/main/resources/META-INF/spring/spring-security.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/298 .
> Fixed redundant bean definitions #298

- parts/JavaConfig-JSP/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
- parts/JavaConfig-NoORM/projectName-domain/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/app/ProjectNameDomainConfig.java
- parts/JavaConfig-Thymeleaf/projectName-web/src/main/java/xxxxxx/yyyyyy/zzzzzz/config/web/SpringMvcConfig.java
(cherry picked from commit 5029907b96d33cbf6b2bd6edb4ae9d262adc4996)
Please review #676.
> [5.10.x] Modify Javadoc #676

- parts/JSP/pom.xml
- parts/Thymeleaf/pom.xml
- testScript/addTestResource.sh
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/JavaConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/XMLConfig/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/AccessDeniedErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/CsrfTokenErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/interceptor/InterceptorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/welcome/HelloTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/error/ErrorTest.java
- testScript/parts/base/projectName-selenium/src/test/java/xxxxxx/yyyyyy/zzzzzz/selenium/welcome/HelloIT.java
Please review #688 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-6948
> migration from Hamcrest to AssertJ #688

- testScript/parts/JavaConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
- testScript/parts/XMLConfig/projectName-web/src/test/java/xxxxxx/yyyyyy/zzzzzz/mocktest/error/MvcErrorTest.java
> minor corrections #688
